include:
  - infrastructure/networking/docker-compose.networks.yaml
  # - infrastructure/kafka/docker-compose.kafka.yaml
  - infrastructure/elastic/docker-compose.elastic.yaml
  # - collectors/docker-compose.collectors.yaml
  # - stream_processing/docker-compose.detection.yaml
  # - response/docker-compose.response.yaml